server:
  port: 8083

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

app:
  service-id: ${APP_SERVICE_ID:ms3-ADMIN-001}
  heartbeat-ms: 7000
  ms2:
    base-url: ${APP_MS2_BASE_URL:http://localhost:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
